apiVersion: v1
kind: Service
metadata:
  name: joomla-svc
  labels:
    app: joomla
    tier: joomla-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30075
  selector:
    app: joomla
    tier: frontend
